[package]
name = "xtask"
description = "Repository automation for RuBase."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"
doc = false

[lints]
workspace = true
